### ISSUE TITLE
Not working together with other protocolib plugins

### ISSUE THREAD

**Issue by loadka95** [MundoSK/MundoSK#3]
So, im using skin changer plugin on my server right now  its SkinRestorer. Its using ProtocolLib for changing skin if im right.
The problem is, when i put MundoSk into my plugin folder, and restart the server. then I try to change my skin ingame and its doesn't change it, just if log out and back in.... I don't know what causing that, but please try to fix it. Thanks! :)

**Comment by TlatoaniHJ** [comment]
What are your versions of MundoSK, ProtocolLib, and Bukkit/Spigot?

**Comment by loadka95** [comment]
Im using the newest from everything.
MundoSk: MundoSK 1.7.5-BETA.7.131
ProtocolLib: VERSION 4.2.1
Spigot: The newest from this site: https://getbukkit.org/spigot

**Comment by TlatoaniHJ** [comment]
I think the problem is that MundoSK's skin changing capabilities are overriding SkinRestorer. You should be able to fix this by going into the config of MundoSK and setting the option 'enable_custom_skin_and_tablist' to false. If you are using MundoSK's tablist features however this will disable them too, so keep that in mind.

**Comment by loadka95** [comment]
Yes, its worked. Thank you very much! :)

**Comment by TlatoaniHJ** [comment]
No problem!
