### ISSUE TITLE
Tablist error on join

### ISSUE THREAD

**Issue by BrettplayMC** [MundoSK/MundoSK#7]
https://hastebin.com/cirudiwiwa.bash

**Comment by TlatoaniHJ** [comment]
Skript version, MundoSK version, and Bukkit/Spigot version please.

**Comment by BrettplayMC** [comment]
Skript dev-25 by Bensku.  Spigot 1.8.8 and MundoSK-BETA.8.46

**Comment by BrettplayMC** [comment]
I believe the plugin "HealthBar" by filoghost is causing this.  I just installed it and this is happening.

**Comment by BrettplayMC** [comment]
It stopped. :)

**Comment by BrettplayMC** [comment]
Though maybe you can add support for it? :D

**Comment by TlatoaniHJ** [comment]
Once I'm free I'll try to test what the problem is, it may be at least a few days to a week until I can do that though.

**Comment by BrettplayMC** [comment]
Ok! :D

**Comment by TlatoaniHJ** [comment]
Sorry for taking so long with it, try this new MundoSK jar: https://github.com/MundoSK/MundoSK/blob/temp/out/artifacts/MundoSK_Test_Tablist/MundoSK_Test_Tablist.jar
Make sure with /ver MundoSK that the version is 1.7.5-BETA.9.9

**Comment by TlatoaniHJ** [comment]
The issue poster hasn’t responded in about half a year, and the relevant code has mostly been rewritten since the version he used for the bug to happen, so this issue will now be closed. If BrettplayMC is still encountering this issue with the latest versions of MundoSK (1.7.5-BETA.10.0 and above) they can open a new issue.
